### ISSUE TITLE
Skill book Window buttons are incorrectly mapped

### ISSUE THREAD

**Issue by nansonzheng** [ryantpayton/HeavenClient#10]
AreaButtons in the Skill Book Window (Default basic key: K) are mapped incorrectly: instead of being row-first, the buttons are arranged column-first. This causes skills being used to be different than what the button shows.

Annotated screenshot of double-clicking a specific empty box attached.

#### Reproduction steps:  
1. Have an explorer character with at least 1 Beginner skill(s) leveled. In theory, this will also work with any other Job, but Beginner skills are all active, making it more apparent.  
2. Use Recovery by double-clicking.  
3. Three Snails, if leveled up, is used instead.  
4. Double-click the blank box below Recovery.  
5. Recovery, if leveled up, is used.  
6. Double-click the blank box 2 boxes below Recovery.  
7. Nimble Feet, if leveled up, is used.

![image](https://user-images.githubusercontent.com/14435972/69791031-a1c20a80-1191-11ea-9af2-5e5c80a09501.png)

**Comment by SomeMushroom** [comment]
Can repro on:
ryantpayton/HeavenClient 67d849
ronancpl/HeavenMS 6d57eb

**Comment by SomeMushroom** [comment]
Also, fwiw, this is how beginner displays are sorted on GMS:

![image](https://user-images.githubusercontent.com/58151192/69897380-4fabf100-1319-11ea-89db-9fbd561a2e18.png)

**Comment by SomeMushroom** [comment]
This issue also occurs in Class I skills. Image below shows where user needs to double click to activate Power Strike.

![image](https://user-images.githubusercontent.com/58151192/69897563-ba5e2c00-131b-11ea-8423-cdcc588c3469.png)

**Comment by nansonzheng** [comment]
Yep, that confirms my theory that the buttons are arranged differently than the clickable areas.
