### ISSUE TITLE
World buttons misaligned in World Select screen

### ISSUE THREAD

**Issue by SomeMushroom** [ryantpayton/HeavenClient#12]
See "Scania" button at upper right. Use coded offsets in UI.wz, where available.

![image](https://user-images.githubusercontent.com/58151192/69887593-c0b9bd00-12b5-11ea-9ecc-ed8123c89beb.png)

**Comment by ryantpayton** [comment]
I think this is similar to #18. Mine looks perfect. Can you double check your UI.nx? What version are you using? I am always running latest UI.nx
