### ISSUE TITLE
Not yet repro'd: Power Strike creates duplicate of character model

### ISSUE THREAD

**Issue by SomeMushroom** [ryantpayton/HeavenClient#16]
```NOTE: Consider removing this ticket if this issue is not common / reproducible```

After becoming a warrior and getting the Power Strike command, somehow I managed to spawn a duplicate version of my character that remained underneath me. The character did not move and despawned once I left `Dances with Balrog`'s sanctuary and re-entered. I would imagine the spawned character was only visible client-side, but I cannot confirm this.

Repro steps (only done once):
1. level up via the GM "!level 10" command
1. assign ap via the GM "!ap 100" command
1. assign 35 points to STR to become eligible to become a warrior
1. become a warrior at `Warriors' Santuary, Victoria Road` by talking with `Dances with Balrog`. 
1. immediately level up `Power Strike` in the skills menu
1. activate a single `Power Strike` by double-clicking the skill in the skills menu

**Comment by ryantpayton** [comment]
I've seen this before and although I can't confirm what caused it. I did have another client running and it that client could not see the duplicated character.

**Comment by lain3d** [comment]
This also occurred when changing jobs or doing anything that caused the SpawnCharHandler to be invoked. This caused the player to be added to Mapchars::chars thus appearing twice. Have a fix, will submit pull request soon.
