### ISSUE TITLE
"x" button misaligned in toolbar of all UI windows

### ISSUE THREAD

**Issue by SomeMushroom** [ryantpayton/HeavenClient#18]
Title. Be sure to use any native offset values in UI.wz, where available.

**Repro steps:**
1. open up any ui window, e.g. skills, abilities, key config

![image](https://user-images.githubusercontent.com/58151192/69897962-dc0de200-1320-11ea-9081-1fc552b82373.png)

**Comment by ryantpayton** [comment]
Double check your wz files. The close button looks completely different than what mine looks like. Also the position for the button is almost always referenced from the wz file, although Nexon doesn't always use this position. Sometimes it needs adjusted by 1 or 2 pixels on the x and/or y.

**Comment by ryantpayton** [comment]
Quick easy fix, button changed from BtClose to BtClose3. Also the origin was shifted three pixels to the left and up. Fixed all references.
