### ISSUE TITLE
!killall command does not clear mobs on the map

### ISSUE THREAD

**Issue by ryantpayton** [ryantpayton/HeavenClient#38]
Using the !killall command does everything expected but the mobs remain after they die. The image of the mob is frozen in the place where they died at. It also starts lagging the game after a few times.

Leaving the map and returning to it does clear the frozen mobs though.

![image](https://user-images.githubusercontent.com/48335966/71303718-91651000-238a-11ea-99ae-e8fa66429282.png)

**Comment by lain3d** [comment]
Fixed, will submit pull request soon.

**Comment by SomeMushroom** [comment]
Assigning per prior comment
