### ISSUE TITLE
Key config window does not warn user to save config before exiting

### ISSUE THREAD

**Issue by SomeMushroom** [ryantpayton/HeavenClient#4]
It's possible for a player to rearrange their key configurations and exit the window without first saving their new config.

Repro steps:
1. Open key config
1. Move 1 action from its current key to a new key
1. Close the key config window via the "x" in the toolbar.
1. Open key config window. Action will be on original key.

While this is correct behavior (in that closing the window does not automatically save the new config) it would be better to warn the player with a dialogue box if they have unsaved changes before allowing them to close the key config window. This is also the behavior in GMS, so resolving this issue gets us feature parity.

**Comment by SomeMushroom** [comment]
Screencap from v209.2:

![image](https://user-images.githubusercontent.com/58151192/69556105-32ba9b00-0f72-11ea-9a17-278daf2ef777.png)

**Comment by SomeMushroom** [comment]
Screencap from v83

![image](https://user-images.githubusercontent.com/58151192/69557027-e1aba680-0f73-11ea-848f-294919be1a6c.png)

**Comment by ryantpayton** [comment]
We should be using only UI elements from the latest stable GMS version. In this scenario, v83 would be irrelevant. Same goes for behavior of the screen.

**Comment by SomeMushroom** [comment]
Noted. Looks like all the notices will need to be remade to use the assets in `UI.wz\UIWindow2.img\KeyConfig`.

Better screencaps from notifications in latest GMS:

Default:
![image](https://user-images.githubusercontent.com/58151192/69750817-afd54400-111b-11ea-9d73-92c2c9054930.png)
![image](https://user-images.githubusercontent.com/58151192/69750845-bfed2380-111b-11ea-9e4b-6fe72f3e13a1.png)

Clear All:
![image](https://user-images.githubusercontent.com/58151192/69750869-cf6c6c80-111b-11ea-9ea5-19866d1df8c1.png)

Change Quickslots:
![image](https://user-images.githubusercontent.com/58151192/69750891-dc895b80-111b-11ea-86b2-2a2df660c7bb.png)
