### ISSUE TITLE
Missing pieces on certain maps

### ISSUE THREAD

**Issue by lain3d** [ryantpayton/HeavenClient#63]
![image](https://user-images.githubusercontent.com/50787417/71444426-ba610a00-26d6-11ea-8653-65309dc04b38.png)
![image](https://user-images.githubusercontent.com/50787417/71444453-e41a3100-26d6-11ea-86b6-8af6e55916e3.png)

**Comment by ryantpayton** [comment]
Are they missing or just offset downwards? It looks like they are there. Just pushed down further.

**Comment by lain3d** [comment]
hmm looks like just offset actually. could it be related to the recent commit involving y offset changes?

**Comment by ryantpayton** [comment]
Nope. Definitely not haha
Within that commit you can see where on MapBackgrounds I believe. I remove the adjustment for it. So it should be in the same place. Plus is was only 10 pxiels. This is a lot more.
I have a fix in the works for this also, so I'll assign myself this.
