### ISSUE TITLE
EULA text and scrollbar on account creation bugged

### ISSUE THREAD

**Issue by SomeMushroom** [ryantpayton/HeavenClient#7]
Text flows outside the window and players do not have the ability to quickly scroll to the bottom by dragging the right navigation bar. Instead, you need to click below the bar repeatedly to reach the bottom, which increments slowly.

![image](https://user-images.githubusercontent.com/58151192/69778792-b4c5e200-1173-11ea-9369-64f1f262fb59.png)

**Comment by nansonzheng** [comment]
This might come down to the solution not having an implementation to draw something within a frame. a new class to handle drawing partial images is likely required.

Also the EULA makes my game's FPS drop to single digits without fail, not sure why. It was a solid 8 FPS when I logged FPS using configuration.h's settings.
