### ISSUE TITLE
Generate Nx files

### ISSUE THREAD

**Issue by yakir4123** [ryantpayton/HeavenClient#76]
Hey guys I found this repo very interesting and I want to join your community.
I compiled the project and now I want to try use it, but couldn't succeeded to generate the specific nx files. I used exactly clean wz files as u mentioned on ur readme. This is the output log
`Working on .\files\Base.wz
Working on .\files\Character.wz
Size mismatch: 1,1,8,2,0
`
If you have clean download for wz or nx I will appriciate that too

**Comment by ryantpayton** [comment]
So it failed on Character.wz?
How are you trying to convert it? Are you using the `start.bat` file?

**Comment by yakir4123** [comment]
Yes and Yes

**Comment by ryantpayton** [comment]
Interesting. I just used the wz files generated from ManagerMsv83.exe
Which can be download here: https://drive.google.com/drive/folders/0BzDsHSr-0V4MYVJ0TWIxd05hYUk

Where did you get the wz files from?

**Comment by yakir4123** [comment]
From what I recall The same ink as yours Ill try again soon

**Comment by ryantpayton** [comment]
Let me know. I didn't write the nx library so it's a bit cryptic but I'm sure we can figure it out.

**Comment by yakir4123** [comment]
OK it solve it + plus I think its worth to say that it necessary to have also the original v83 map.wz
Thanks cant wait to see what I can do with that

**Comment by ryantpayton** [comment]
Map.nx should be the v83 Map.wz
The MapPretty/MapLatest/Map001 is all from later versions.

Please let me know if you have additional questions. We have a discord as well if you want to chat in a quicker manner.
